---
name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby_version: "2.7.2"
            rails_version: "6.1"
          - ruby_version: "2.7.2"
            rails_version: "7.0"

          - ruby_version: "3.1.4"
            rails_version: "6.1"
          - ruby_version: "3.1.4"
            rails_version: "7.0"
    name: "Tests on Ruby ${{ matrix.ruby_version }} and Rails ${{ matrix.rails_version }}"
    env:
      BUNDLE_GEMFILE: "Gemfile.rails-${{ matrix.rails_version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby_version }}"
      - name: Bundle
        run: |
          gem install bundler:2.1.4
          bundle install --no-deployment
      - name: Run tests
        run: bundle exec rspec
